services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    networks:
      - my_network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    tty: true
    restart: always
    networks:
      - my_network
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama:/root/.ollama

networks:
  my_network:
    driver: bridge

volumes:
  nextjs: {}
  ollama: {}